// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkhgcnxscwghrmhczlsz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1raGdjbnhzY3dnaHJtaGN6bHN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNTcxMjMsImV4cCI6MjA2MTgzMzEyM30.mgSBZVZIci-H2OcbkoNGHiYqkDQsP-wSq4FoXLlJi5c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);